// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpILt29AByIX7QkSBXxHDk1v4Bl4Kf0_8',
    appId: '1:814418475338:web:0233f20411cc68f17329b3',
    messagingSenderId: '814418475338',
    projectId: 'rxseek-b60ba',
    authDomain: 'rxseek-b60ba.firebaseapp.com',
    storageBucket: 'rxseek-b60ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHzXQcmcNqCEyiruNpfVrVh63W0LJP3Ng',
    appId: '1:814418475338:android:a4ee904d8f89c6c87329b3',
    messagingSenderId: '814418475338',
    projectId: 'rxseek-b60ba',
    storageBucket: 'rxseek-b60ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdbuzLDsTpIeG7wvRUQfJ6bJZvGrJbnhE',
    appId: '1:814418475338:ios:94e04dec2c115fe77329b3',
    messagingSenderId: '814418475338',
    projectId: 'rxseek-b60ba',
    storageBucket: 'rxseek-b60ba.appspot.com',
    iosBundleId: 'com.example.rxseekV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdbuzLDsTpIeG7wvRUQfJ6bJZvGrJbnhE',
    appId: '1:814418475338:ios:94e04dec2c115fe77329b3',
    messagingSenderId: '814418475338',
    projectId: 'rxseek-b60ba',
    storageBucket: 'rxseek-b60ba.appspot.com',
    iosBundleId: 'com.example.rxseekV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpILt29AByIX7QkSBXxHDk1v4Bl4Kf0_8',
    appId: '1:814418475338:web:d8edceff71e1b1057329b3',
    messagingSenderId: '814418475338',
    projectId: 'rxseek-b60ba',
    authDomain: 'rxseek-b60ba.firebaseapp.com',
    storageBucket: 'rxseek-b60ba.appspot.com',
  );
}
